/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mscb.tick.gui.main;

import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import mscb.tick.negocio.entidades.EstadoActualPgm;
import mscb.tick.negocio.entidades.EstadosPgm;
import mscb.tick.negocio.EstadoActualPgmServ;
import mscb.tick.negocio.EstadosPgmServ;
import mscb.tick.util.MenuP;

/**
 *
 * @author Administrador
 */
public class EstadoPGMP extends MenuP {
    private static EstadoPGMP estePanel;
    private EstadoPGMD mainFrame;
    Main mainFrameO;
    private EstadosPgmServ serviciosPgm;
    private EstadoActualPgmServ serviciosPgmA;
    private Date fecha;
    /**
     * Creates new form EstadoPGMP
     */
    public EstadoPGMP(EstadoPGMD mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        setSize(260, 360);
        setVisible(true);
        serviciosPgm = new EstadosPgmServ();
        serviciosPgmA = new EstadoActualPgmServ();
        lbl_estado.setText(serviciosPgmA.traerEstadoActual(1).getFkEstadoPgm().getEstado());
        setearColor();
        cargarComboBoxEstados();
    }
    
    public static EstadoPGMP getPanelPgm(EstadoPGMD mainFrame){
        if(estePanel == null ){
            estePanel = new EstadoPGMP(mainFrame);
        }
        return estePanel;
    }
    
    public void cargarComboBoxEstados(){
        List<EstadosPgm> miLista = serviciosPgm.traerTodos();
        for(int i = 0 ; i < miLista.size(); i++){
            cmbx_estadosPgm.addItem(miLista.get(i));
        }
    }
    
    private void setearColor(){
        int i = serviciosPgmA.traerEstadoActual(1).getFkEstadoPgm().getIdEstado();
        switch (i) {
 
        case 1:
            jp_color.setBackground(Color.GREEN);
            break;
        case 2:
            jp_color.setBackground(Color.BLUE);
            break;
        case 3:
            jp_color.setBackground(Color.ORANGE);
            break;
        case 4:
            jp_color.setBackground(Color.RED);
            break;
        case 5:
            jp_color.setBackground(Color.GRAY);
            break;
     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_estado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        cmbx_estadosPgm = new javax.swing.JComboBox();
        jp_color = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado PGM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bradley Hand ITC", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estado PGM actual:");

        lbl_estado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_estado.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cambiar a:");

        btn_volver.setBackground(new java.awt.Color(153, 153, 153));
        btn_volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(153, 153, 153));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        cmbx_estadosPgm.setBackground(new java.awt.Color(153, 153, 153));
        cmbx_estadosPgm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbx_estadosPgm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_estadosPgmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_colorLayout = new javax.swing.GroupLayout(jp_color);
        jp_color.setLayout(jp_colorLayout);
        jp_colorLayout.setHorizontalGroup(
            jp_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jp_colorLayout.setVerticalGroup(
            jp_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbx_estadosPgm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jp_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 48, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jp_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbx_estadosPgm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_volver)
                    .addComponent(btn_guardar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        mainFrame.setVisible(false);
        estePanel = null;
        mainFrame.dispose();
        mainFrame = null;
        System.gc();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        fecha = new Date();
        EstadoActualPgm eap = new EstadoActualPgm();
        eap.setFecha(fecha);
        eap.setFkEstadoPgm((EstadosPgm) cmbx_estadosPgm.getSelectedItem());
        eap.setId(1);
        if(serviciosPgmA.modificarEstadoActual(eap)){
            JOptionPane.showMessageDialog(null, "Estado actualizado");
            lbl_estado.setText(eap.getFkEstadoPgm().getEstado());
            setearColor();
        }else{
            JOptionPane.showMessageDialog(null, "Error al actualizar estado del PGM","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void cmbx_estadosPgmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_estadosPgmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbx_estadosPgmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox cmbx_estadosPgm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jp_color;
    private javax.swing.JLabel lbl_estado;
    // End of variables declaration//GEN-END:variables
}
