/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mscb.tick.main;

import com.sun.management.OperatingSystemMXBean;
import java.lang.management.ManagementFactory;
import mscb.tick.util.MenuP;

/**
 *
 * @author Administrador
 */
public class InformacionSistema extends MenuP {
    InfoD mainFrame;
    private static InformacionSistema estePanel;
    private OperatingSystemMXBean mxbean;
    /**
     * Creates new form System
     */
    private InformacionSistema(InfoD mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
         mxbean = (OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean();
        setSize(230, 260);
        setVisible(true);
        lbl_os.setText(System.getProperty("os.name"));
        lbl_osarc.setText(System.getProperty("os.arch"));
        lbl_osvers.setText(System.getProperty("os.version"));
        lbl_javavers.setText(System.getProperty("java.version"));
        lbl_ramT.setText(mxbean.getTotalPhysicalMemorySize()/1073741824 + " GB "); 
        lbl_ramD.setText(mxbean.getFreePhysicalMemorySize()/1048576 + " MB ");
    }
    
    public static InformacionSistema getInformacionSistema(InfoD mainFrame){
        if(estePanel == null){
            estePanel = new InformacionSistema(mainFrame);
        }
        return estePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_gud = new javax.swing.JButton();
        lbl_os = new javax.swing.JLabel();
        lbl_osarc = new javax.swing.JLabel();
        lbl_osvers = new javax.swing.JLabel();
        lbl_javavers = new javax.swing.JLabel();
        lbl_javavers1 = new javax.swing.JLabel();
        lbl_javavers2 = new javax.swing.JLabel();
        lbl_javavers3 = new javax.swing.JLabel();
        lbl_javavers4 = new javax.swing.JLabel();
        lbl_javavers5 = new javax.swing.JLabel();
        lbl_javavers6 = new javax.swing.JLabel();
        lbl_ramT = new javax.swing.JLabel();
        lbl_ramD = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion del Sistema", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        btn_gud.setBackground(new java.awt.Color(153, 153, 153));
        btn_gud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_gud.setText("gud");
        btn_gud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gudActionPerformed(evt);
            }
        });

        lbl_os.setForeground(new java.awt.Color(255, 255, 255));

        lbl_osarc.setForeground(new java.awt.Color(255, 255, 255));

        lbl_osvers.setForeground(new java.awt.Color(255, 255, 255));

        lbl_javavers.setForeground(new java.awt.Color(255, 255, 255));

        lbl_javavers1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_javavers1.setText("Arquitectura:");

        lbl_javavers2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_javavers2.setText("SO:");

        lbl_javavers3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_javavers3.setText("Version de SO:");

        lbl_javavers4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_javavers4.setText("Version Java:");

        lbl_javavers5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_javavers5.setText("RAM Total:");

        lbl_javavers6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_javavers6.setText("RAM Disponible:");

        lbl_ramT.setForeground(new java.awt.Color(255, 255, 255));

        lbl_ramD.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_gud)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_javavers1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_javavers4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_javavers2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_javavers3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_os, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_osvers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_osarc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lbl_javavers, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_javavers6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ramD, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_javavers5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ramT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_os, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_javavers2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_javavers4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_javavers3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_osarc, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_javavers1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_osvers, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_javavers, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_javavers5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ramT, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_javavers6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ramD, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btn_gud)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gudActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        mainFrame.panelInfoP();
        estePanel = null;
        System.gc();
    }//GEN-LAST:event_btn_gudActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gud;
    private javax.swing.JLabel lbl_javavers;
    private javax.swing.JLabel lbl_javavers1;
    private javax.swing.JLabel lbl_javavers2;
    private javax.swing.JLabel lbl_javavers3;
    private javax.swing.JLabel lbl_javavers4;
    private javax.swing.JLabel lbl_javavers5;
    private javax.swing.JLabel lbl_javavers6;
    private javax.swing.JLabel lbl_os;
    private javax.swing.JLabel lbl_osarc;
    private javax.swing.JLabel lbl_osvers;
    private javax.swing.JLabel lbl_ramD;
    private javax.swing.JLabel lbl_ramT;
    // End of variables declaration//GEN-END:variables
}
