/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mscb.tick.asuntoSecundarios.vista;

import javax.swing.JFrame;
import mscb.tick.entidades.Asuntos;
import mscb.tick.main.Main;

/**
 *
 * @author Administrador
 */
public class NuevoAsuntoSecD extends javax.swing.JDialog {
    Main mainFrame;
    private NuevoAsuntoSec nuevoAsunto;
    /**
     * Creates new form NuevoAsuntoSecD
     */
    public NuevoAsuntoSecD(java.awt.Frame parent, boolean modal,Asuntos miAsuntoPP) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(0);
        setResizable(false);
        this.mainFrame = (Main) parent;
        setSize(260, 320);
        setTitle("Nuevo servicio");
        setLocationRelativeTo(parent);
        nuevoAsunto(miAsuntoPP);
        setVisible(true);
    }

    private NuevoAsuntoSecD(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void nuevoAsunto(Asuntos miAsuntoPP){
        nuevoAsunto = NuevoAsuntoSec.getNuevoAsunto(this,mainFrame,miAsuntoPP);
        
        if(!nuevoAsunto.isVisible() == false){
            getContentPane().add(nuevoAsunto);
        }else{
            nuevoAsunto.setVisible(true);
        }
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoAsuntoSecD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoAsuntoSecD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoAsuntoSecD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoAsuntoSecD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoAsuntoSecD dialog = new NuevoAsuntoSecD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
