/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mscb.tick.login;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mscb.tick.main.Main;
import mscb.tick.util.MenuP;

/**
 *
 * @author Administrador
 */
public class MenuPrincipal extends MenuP {
    private static String fondo;
    private Image background;
    private static MenuPrincipal menuP;
    Main mainFrame;
    /**
     * Creates new form MenuPrincipal
     */
       
    private MenuPrincipal(Main mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        mainFrame.btn_mini.setVisible(true);
        initComponents();
        setSize(800, 600);
        setVisible(true);
        mainFrame.setSize(800, 600);
        mainFrame.setLocationRelativeTo(null);
        mainFrame.setTitle("Ticketneitor");
    }
    
    public static MenuPrincipal getMenuPrincipal(Main mainFrame){
        if(menuP == null){
            menuP = new MenuPrincipal(mainFrame);
        }
        return menuP;
    }
    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_admTick = new javax.swing.JToggleButton();
        btn_salir = new javax.swing.JToggleButton();
        btn_logout = new javax.swing.JToggleButton();
        btn_admusu = new javax.swing.JToggleButton();
        btn_info = new javax.swing.JToggleButton();
        btn_nuevo = new javax.swing.JToggleButton();
        btn_cambiarClave = new javax.swing.JToggleButton();
        btn_asignar = new javax.swing.JToggleButton();
        btn_misTickets = new javax.swing.JToggleButton();
        btn_admAsun = new javax.swing.JToggleButton();
        btn_admAsunSec = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ticketneitar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bradley Hand ITC", 0, 24), java.awt.Color.white)); // NOI18N

        btn_admTick.setBackground(new java.awt.Color(0, 102, 204));
        btn_admTick.setForeground(new java.awt.Color(255, 255, 255));
        btn_admTick.setText("administrar tickets");
        btn_admTick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admTickActionPerformed(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(0, 102, 204));
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(0, 102, 204));
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("cerrar sesion");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_admusu.setBackground(new java.awt.Color(0, 102, 204));
        btn_admusu.setForeground(new java.awt.Color(255, 255, 255));
        btn_admusu.setText("administrar usuarios");
        btn_admusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admusuActionPerformed(evt);
            }
        });

        btn_info.setBackground(new java.awt.Color(0, 102, 204));
        btn_info.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_info.setForeground(new java.awt.Color(255, 255, 255));
        btn_info.setText("?");
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });

        btn_nuevo.setBackground(new java.awt.Color(0, 102, 204));
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setText("nuevo pedido a sistemas");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_cambiarClave.setBackground(new java.awt.Color(0, 102, 204));
        btn_cambiarClave.setForeground(new java.awt.Color(255, 255, 255));
        btn_cambiarClave.setText("cambiar mi clave");
        btn_cambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiarClaveActionPerformed(evt);
            }
        });

        btn_asignar.setBackground(new java.awt.Color(0, 102, 204));
        btn_asignar.setForeground(new java.awt.Color(255, 255, 255));
        btn_asignar.setText("asignar asuntos");
        btn_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asignarActionPerformed(evt);
            }
        });

        btn_misTickets.setBackground(new java.awt.Color(0, 102, 204));
        btn_misTickets.setForeground(new java.awt.Color(255, 255, 255));
        btn_misTickets.setText("misTickets");
        btn_misTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_misTicketsActionPerformed(evt);
            }
        });

        btn_admAsun.setBackground(new java.awt.Color(0, 102, 204));
        btn_admAsun.setForeground(new java.awt.Color(255, 255, 255));
        btn_admAsun.setText("administrar asuntos");
        btn_admAsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admAsunActionPerformed(evt);
            }
        });

        btn_admAsunSec.setBackground(new java.awt.Color(0, 102, 204));
        btn_admAsunSec.setForeground(new java.awt.Color(255, 255, 255));
        btn_admAsunSec.setText("administrar asuntos secundarios");
        btn_admAsunSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admAsunSecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_info))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(btn_cambiarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_admTick, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_admAsunSec, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_misTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btn_admusu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_admAsun, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_info, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_misTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_admusu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_admAsun, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_admAsunSec, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_admTick, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cambiarClave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
        // TODO add your handling code here:
        mainFrame.ventanaInfo();
    }//GEN-LAST:event_btn_infoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Seguro desea salir?","Confirmar",JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_admTickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admTickActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mainFrame.tickets();
    }//GEN-LAST:event_btn_admTickActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        mainFrame.nuevoTicket();
        this.setVisible(false);
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Seguro desea salir?","Confirmar",JOptionPane.YES_NO_OPTION)==0){
            this.setVisible(false);
            menuP = null;
            System.gc();
            mainFrame.ventanaLogin();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_admusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admusuActionPerformed
        // TODO add your handling code here:
        mainFrame.ventanausuarios();
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_admusuActionPerformed

    private void btn_cambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiarClaveActionPerformed
        // TODO add your handling code here:
        mainFrame.cambiarClave();
    }//GEN-LAST:event_btn_cambiarClaveActionPerformed

    private void btn_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asignarActionPerformed
        // TODO add your handling code here:
        mainFrame.asignarAsuntosEncargado();
        this.setVisible(false);
    }//GEN-LAST:event_btn_asignarActionPerformed

    private void btn_misTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_misTicketsActionPerformed
        // TODO add your handling code here:
        mainFrame.miTickets();
        this.setVisible(false);
    }//GEN-LAST:event_btn_misTicketsActionPerformed

    private void btn_admAsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admAsunActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mainFrame.asuntos();
    }//GEN-LAST:event_btn_admAsunActionPerformed

    private void btn_admAsunSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admAsunSecActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mainFrame.asuntoSecundarios();
    }//GEN-LAST:event_btn_admAsunSecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_admAsun;
    private javax.swing.JToggleButton btn_admAsunSec;
    private javax.swing.JToggleButton btn_admTick;
    private javax.swing.JToggleButton btn_admusu;
    private javax.swing.JToggleButton btn_asignar;
    private javax.swing.JToggleButton btn_cambiarClave;
    private javax.swing.JToggleButton btn_info;
    private javax.swing.JToggleButton btn_logout;
    private javax.swing.JToggleButton btn_misTickets;
    private javax.swing.JToggleButton btn_nuevo;
    private javax.swing.JToggleButton btn_salir;
    // End of variables declaration//GEN-END:variables
}
