/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mscb.tick.gui.estadisticas;

import java.util.List;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mscb.tick.gui.main.Main;
import mscb.tick.negocio.AreaServ;
import mscb.tick.negocio.TicketServ;
import mscb.tick.negocio.entidades.Estadisticas;
import mscb.tick.util.MenuP;

/**
 * Estadisticas de ticket que se enviaron a las areas
 * @author Administrador
 */
public class EstadisticasAreasEmitidos extends MenuP {
    private static EstadisticasAreasEmitidos estePanel;
    /**
     * Creates new form EstadisticasAreas
     */
    private EstadisticasAreasEmitidos() {
        initComponents();
        setVisible(true);
        llenarTabla();
    }
    
    public static EstadisticasAreasEmitidos getEstadisticasAreasEmitidos(){
        if(estePanel == null){
            estePanel = new EstadisticasAreasEmitidos();
        }
        return estePanel;
    }
    
    public void llenarTabla(){
        List<Estadisticas> miLista = TicketServ.getTicketServ().getEstadisticasPorArea();
        DefaultTableModel modelo = (DefaultTableModel) jt_estadisticas.getModel();
        String[] v = new String[2];
        
        for(int i = 0; i < miLista.size(); i++){
            v[0] = miLista.get(i).getNombre();
            v[1] = miLista.get(i).getCantidad().toString();
            modelo.addRow(v);
        }
        revalidate();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_estadisticas = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tickets emitidos por area", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), new java.awt.Color(0, 108, 118)))); // NOI18N

        jt_estadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Areas", "Cantidad de tickets"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_estadisticas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jt_estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_estadisticasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_estadisticas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_estadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_estadisticasMouseClicked
        // TODO add your handling code here:
        if(evt.getSource() == jt_estadisticas){
            if(evt.getClickCount() == 2){
                if((jt_estadisticas.getSelectedRow() != -1)&&(jt_estadisticas.getSelectedRowCount() == 1)){
                    Main.getMainFrame().estadisticasPorUsuario(AreaServ.getAreaServ().getAreaPorNombre(jt_estadisticas.getValueAt(jt_estadisticas.getSelectedRow(), 0).toString()).getIdArea());
                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_jt_estadisticasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_estadisticas;
    // End of variables declaration//GEN-END:variables
}
