/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mscb.tick.gui.empleados;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import mscb.tick.negocio.EmpleadoServ;
import mscb.tick.negocio.entidades.Empleados;
import mscb.tick.gui.main.Main;
import mscb.tick.util.MenuP;

/**
 *
 * @author Administrador
 */
public class EmpleadosV extends MenuP {
    private static EmpleadosV estePanel;
    Main mainFrame;
    private EmpleadoServ serviciosE;
    private List<Empleados> miLista;
    private DefaultTableModel modelo;
    
    /**
     * Creates new form EmpeladosV
     */
    private EmpleadosV(Main mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        setVisible(true);
        serviciosE = EmpleadoServ.getEmpleadoServ();
        validarPermisos();
        btn_eliminar.setVisible(false);
        modelo = (DefaultTableModel) jt_empleados.getModel();
        llenarTabla(cargarTodosLosEmpelados());
    }
    
    public static EmpleadosV getEmpeladosV(Main mainFrame){
        if(estePanel == null){
            estePanel = new EmpleadosV(mainFrame);
        }
        return estePanel;
    }
    
     private void validarPermisos(){
        //boton eliminar
        if(!mainFrame.validarPermisos(41)){
            btn_eliminar.setEnabled(false);
            btn_eliminar.setVisible(false);
        }else{
            btn_eliminar.setEnabled(true);
            btn_eliminar.setVisible(true); 
        }
        //boton modificar
        if(!mainFrame.validarPermisos(43)){
            btn_modificar.setEnabled(false);
            btn_modificar.setVisible(false);
        }else{
            btn_modificar.setEnabled(true);
            btn_modificar.setVisible(true); 
        }
        //boton nuevo
        if(!mainFrame.validarPermisos(42)){
            btn_nuevo.setEnabled(false);
            btn_nuevo.setVisible(false);
        }else{
            btn_nuevo.setEnabled(true);
            btn_nuevo.setVisible(true); 
        }
     }
     
    public void llenarTabla(List<Empleados> aCargar){
        String v[] = new String[6];
        vaciarTabla(jt_empleados);
        
        for(int i = 0; i < aCargar.size(); i++){
            v[0] = aCargar.get(i).getIdEmpleado().toString();
            v[1] = aCargar.get(i).getNombre();
            v[2] = aCargar.get(i).getApellido();
            v[3] = aCargar.get(i).getDocumento();
            v[4] = aCargar.get(i).getLegajo().toString();
            v[5] = aCargar.get(i).getFkArea().getNombreArea();
            modelo.addRow(v);
        }
        revalidate();
    }
    
    public List<Empleados> cargarTodosLosEmpelados(){
        miLista = serviciosE.traerTodos();
        return miLista;
    }
    
    public List<Empleados> cargarEmpleadosBuscados(String patron){
        miLista = serviciosE.traerEmpleados(patron);
        return miLista;
    }
    
    private void vaciarTabla(JTable tabla) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            int filas = tabla.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_empleados = new javax.swing.JTable();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_busca = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jt_empleados.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jt_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Empelado", "Nombre", "Apellido", "DNI", "Legajo", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_empleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jt_empleados);

        btn_eliminar.setBackground(new java.awt.Color(153, 153, 153));
        btn_eliminar.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(0, 108, 118));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mscb/tick/resources/imagenes/icons/delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_modificar.setBackground(new java.awt.Color(153, 153, 153));
        btn_modificar.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(0, 108, 118));
        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mscb/tick/resources/imagenes/icons/edit.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_nuevo.setBackground(new java.awt.Color(153, 153, 153));
        btn_nuevo.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(0, 108, 118));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mscb/tick/resources/imagenes/icons/add.png"))); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_atras.setBackground(new java.awt.Color(153, 153, 153));
        btn_atras.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_atras.setForeground(new java.awt.Color(0, 108, 118));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mscb/tick/resources/imagenes/icons/back-arrow.png"))); // NOI18N
        btn_atras.setText("Volver");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 108, 118));
        jLabel1.setText("Buscar:");

        txt_busca.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        txt_busca.setForeground(new java.awt.Color(0, 108, 118));
        txt_busca.setText("por Nombre,Apellido o Legajo");
        txt_busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscaMouseClicked(evt);
            }
        });
        txt_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscaActionPerformed(evt);
            }
        });
        txt_busca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_atras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar)
                        .addGap(14, 14, 14)
                        .addComponent(btn_nuevo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar)
                    .addComponent(btn_nuevo)
                    .addComponent(btn_atras)
                    .addComponent(btn_eliminar))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscaActionPerformed
        // TODO add your handling code here:
        if(!txt_busca.getText().isEmpty()){
            llenarTabla(cargarEmpleadosBuscados(txt_busca.getText()));
        }
    }//GEN-LAST:event_txt_buscaActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        // TODO add your handling code here:
        mainFrame.menuPrincipal();
        setVisible(false);
        estePanel = null;
        System.gc();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void txt_buscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscaMouseClicked
        // TODO add your handling code here:
        txt_busca.setText("");
    }//GEN-LAST:event_txt_buscaMouseClicked

    private void txt_buscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscaKeyTyped
        // TODO add your handling code here:
        if(!txt_busca.getText().isEmpty()){
            llenarTabla(cargarEmpleadosBuscados(txt_busca.getText()));
        }
    }//GEN-LAST:event_txt_buscaKeyTyped

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mainFrame.nuevoEmpleado();
        estePanel = null;
        System.gc();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here: se puede hacer desde la jTable tomando los campos modificados
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_empleados;
    private javax.swing.JTextField txt_busca;
    // End of variables declaration//GEN-END:variables
}
