/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mscb.tick.gui.asuntos;

import java.util.List;
import javax.swing.JOptionPane;
import mscb.tick.negocio.AreaServ;
import mscb.tick.negocio.AsuntoPrincipalServ;
import mscb.tick.negocio.entidades.Areas;
import mscb.tick.negocio.entidades.Asuntos;
import mscb.tick.gui.main.Main;
import mscb.tick.util.MenuP;

/**
 *
 * @author Administrador
 */
public class NuevoAsunto extends MenuP {
    NuevoAsuntoD mainFrame;
    Main mainFrameO;
    private static NuevoAsunto nuevoAsunto;
    private AsuntoPrincipalServ serviciosA;
    private Asuntos miAsunto;
    private AsuntosPrin asuntos;
    private Areas miArea;
    /**
     * Creates new form NuevoAsunto singleton
     */
    private NuevoAsunto(NuevoAsuntoD mainFrame,Main mainFrameO,Areas miArea) {
        initComponents();
        this.miArea = miArea;
        this.mainFrameO = mainFrameO;
        this.mainFrame = mainFrame;
        if(miArea.getNombreArea().equals("nuevo")){
            cargarComboBox();
        }else{
            cmbx_areas.setVisible(false);
            lblArea.setText(miArea.getNombreArea());
        }
        txt_nombreAsunto.requestFocus();
        setVisible(true);
    }
    
    public static NuevoAsunto getNuevoAsunto(NuevoAsuntoD mainFrame,Main mainFrameO,Areas miArea){
        if(nuevoAsunto == null){
            nuevoAsunto = new NuevoAsunto(mainFrame,mainFrameO, miArea);
        }
        return nuevoAsunto;
    }
    
    private void cargarComboBox(){
        AreaServ serviciosAr = AreaServ.getAreaServ();
        List<Areas> miLista = serviciosAr.traerTodas();
        for(int i = 0; i < miLista.size();i++){
            cmbx_areas.addItem(miLista.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nombreAsunto = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        cmbx_areas = new javax.swing.JComboBox();
        cmbx_visible = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Asunto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), new java.awt.Color(0, 108, 118))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 108, 118));
        jLabel1.setText("Nombre del asunto:");

        txt_nombreAsunto.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        btn_salir.setBackground(new java.awt.Color(153, 153, 153));
        btn_salir.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(0, 108, 118));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mscb/tick/resources/imagenes/icons/close.png"))); // NOI18N
        btn_salir.setText("Cerrar");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_nuevo.setBackground(new java.awt.Color(153, 153, 153));
        btn_nuevo.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(0, 108, 118));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mscb/tick/resources/imagenes/icons/save.png"))); // NOI18N
        btn_nuevo.setText("Guardar");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 108, 118));
        jLabel2.setText("Area:");

        lblArea.setBackground(new java.awt.Color(0, 102, 204));
        lblArea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));

        cmbx_areas.setBackground(new java.awt.Color(153, 153, 153));
        cmbx_areas.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        cmbx_areas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", " " }));
        cmbx_areas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_areasActionPerformed(evt);
            }
        });

        cmbx_visible.setBackground(new java.awt.Color(153, 153, 153));
        cmbx_visible.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        cmbx_visible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        cmbx_visible.setSelectedIndex(1);
        cmbx_visible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_visibleActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 108, 118));
        jLabel3.setText("Visible:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_salir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_nuevo))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cmbx_visible, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_nombreAsunto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbx_areas, javax.swing.GroupLayout.Alignment.LEADING, 0, 385, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbx_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbx_visible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombreAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mainFrame.setVisible(false);
        nuevoAsunto = null;
        mainFrame = null;
        System.gc();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        if(!txt_nombreAsunto.getText().trim().isEmpty()){
            serviciosA = AsuntoPrincipalServ.getAsuntoPrincipalServ();
            miAsunto = new Asuntos();
            miAsunto.setNombre(txt_nombreAsunto.getText());
            if(cmbx_visible.getSelectedItem().equals("Si")){
                miAsunto.setVisible(true);
            }
            if(cmbx_visible.getSelectedItem().equals("No")){
                miAsunto.setVisible(false);
            }

            if(miArea.getNombreArea().equals("nuevo")){
                miAsunto.setFkArea((Areas) cmbx_areas.getSelectedItem());
            }else{
                miAsunto.setFkArea(miArea);
            }

            if(serviciosA.nuevoAsunto(miAsunto)){
                asuntos = AsuntosPrin.getAsuntos(mainFrameO);
                if(!miArea.getNombreArea().equals("nuevo")){
                    asuntos.llenarTabla();
                }                    
            }else{
                JOptionPane.showMessageDialog(mainFrame, "Error al cargar asunto!");
            }
            this.setVisible(false);
            txt_nombreAsunto.requestFocus();
            mainFrame.setVisible(false);
            nuevoAsunto = null;
            mainFrame = null;
            System.gc();
        }
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void cmbx_areasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_areasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbx_areasActionPerformed

    private void cmbx_visibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_visibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbx_visibleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox cmbx_areas;
    private javax.swing.JComboBox cmbx_visible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblArea;
    private javax.swing.JTextField txt_nombreAsunto;
    // End of variables declaration//GEN-END:variables
}
