/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mscb.tick.encargadoAsuntos.vista;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import mscb.tick.asuntoPrincipal.servicios.AsuntoPrincipalServ;
import mscb.tick.asuntoSecundario.servicios.AsuntoSecundarioServ;
import mscb.tick.entidades.AsuntoPrincipal;
import mscb.tick.entidades.AsuntoSecundario;
import mscb.tick.entidades.Usuario;
import mscb.tick.main.Main;
import mscb.tick.usuarios.servicios.UsuarioServ;
import mscb.tick.util.MenuP;

/**
 *
 * @author Administrador
 */
public class EncargadoAsuntos extends MenuP {

    Main mainFrame;
    private static EncargadoAsuntos estePanel;
    private List<Usuario> miListaU;
    private UsuarioServ serviciosU;
    private List<AsuntoSecundario> miListaA;
    private AsuntoSecundarioServ serviciosA;
    private List<AsuntoPrincipal> miListaP;
    private AsuntoPrincipalServ serviciosP;
    private DefaultTableModel modelo;

    /**
     * Creates new form EncargadoAsuntos
     */
    private EncargadoAsuntos(Main mainFrame) {
        initComponents();
        modelo = (DefaultTableModel) jt_asuntos.getModel();
        cmbx_asuntosP.setVisible(false);
        cmbx_asuntosS.setVisible(false);
        lbl_asuntos.setVisible(false);
        btn_agregar.setVisible(false);
        miListaA = new ArrayList<>();
        this.mainFrame = mainFrame;
        this.setSize(800, 600);
        this.setVisible(true);
        cargarComboBoxUsuarios();
        cargarComboBoxAsuntoP();

    }

    public static EncargadoAsuntos getEncargadoAsuntos(Main mainFrame) {
        if (estePanel == null) {
            estePanel = new EncargadoAsuntos(mainFrame);
        }
        return estePanel;
    }

    private void cargarComboBoxUsuarios() {
        serviciosU = new UsuarioServ();
        miListaU = new ArrayList<>();
        miListaU = serviciosU.traerSistemas();

        for (int i = 0; i < miListaU.size(); i++) {
            cmbx_usuarios.addItem(miListaU.get(i));
        }
    }

    private void cargarComboBoxAsuntoS() {
        serviciosA = new AsuntoSecundarioServ();
        miListaA = serviciosA.traerPorAreaPrincipal((AsuntoPrincipal) cmbx_asuntosP.getSelectedItem());
        cmbx_asuntosS.removeAllItems();
        for (int i = 0; i < miListaA.size(); i++) {
            cmbx_asuntosS.addItem(miListaA.get(i));
        }

    }

    private void cargarComboBoxAsuntoP() {
        serviciosP = new AsuntoPrincipalServ();
        miListaP = new ArrayList<>();
        miListaP = serviciosP.traerTodos();
        for (int i = 0; i < miListaP.size(); i++) {
            cmbx_asuntosP.addItem(miListaP.get(i));
        }
    }

    private void cargarTabla() {
        vaciarTabla(jt_asuntos);
        
        String v[] = new String[2];
        List<AsuntoSecundario> aux = new ArrayList<>();
        
        int a = miListaU.get(miListaU.indexOf(cmbx_usuarios.getSelectedItem())).getAsuntoSecundarioCollection().size();
        List<AsuntoSecundario> miLi = (List<AsuntoSecundario>) miListaU.get(miListaU.indexOf(cmbx_usuarios.getSelectedItem())).getAsuntoSecundarioCollection();

        for (int i = 0; i < a; i++) {
            v[0] = miLi.get(i).getPertenece().getNombre();
            v[1] = miLi.get(i).getNombreasuntoS();
            modelo.addRow(v);
        }
    }

    private void vaciarTabla(JTable tabla) {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            int filas = tabla.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbx_usuarios = new javax.swing.JComboBox();
        cmbx_asuntosP = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_asuntos = new javax.swing.JTable();
        btn_volver = new javax.swing.JButton();
        btn_quitar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_asuntos = new javax.swing.JLabel();
        cmbx_asuntosS = new javax.swing.JComboBox();
        btn_agregar = new javax.swing.JButton();
        lbl_asuntos1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignar asuntos", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bradley Hand ITC", 0, 24), java.awt.Color.white)); // NOI18N

        cmbx_usuarios.setBackground(new java.awt.Color(0, 102, 204));
        cmbx_usuarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbx_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_usuarios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbx_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_usuariosActionPerformed(evt);
            }
        });

        cmbx_asuntosP.setBackground(new java.awt.Color(0, 102, 204));
        cmbx_asuntosP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbx_asuntosP.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_asuntosP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbx_asuntosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_asuntosPActionPerformed(evt);
            }
        });

        jt_asuntos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asuntos", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_asuntos);

        btn_volver.setBackground(new java.awt.Color(0, 102, 204));
        btn_volver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver.setText("volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        btn_quitar.setBackground(new java.awt.Color(0, 102, 204));
        btn_quitar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_quitar.setForeground(new java.awt.Color(255, 255, 255));
        btn_quitar.setText("quitar");
        btn_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(0, 102, 204));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("guardar");

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elegir un usuario:");

        lbl_asuntos.setFont(new java.awt.Font("Bradley Hand ITC", 0, 18)); // NOI18N
        lbl_asuntos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_asuntos.setText("Asuntos:");

        cmbx_asuntosS.setBackground(new java.awt.Color(0, 102, 204));
        cmbx_asuntosS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbx_asuntosS.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_asuntosS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbx_asuntosS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_asuntosSActionPerformed(evt);
            }
        });

        btn_agregar.setBackground(new java.awt.Color(0, 102, 204));
        btn_agregar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("+");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        lbl_asuntos1.setFont(new java.awt.Font("Bradley Hand ITC", 0, 18)); // NOI18N
        lbl_asuntos1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_asuntos1.setText("Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(btn_quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbx_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_asuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))
                            .addComponent(cmbx_asuntosP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmbx_asuntosS, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_asuntos1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_agregar)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_guardar, btn_quitar, btn_volver});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbx_asuntosP, cmbx_asuntosS});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_asuntos)
                    .addComponent(lbl_asuntos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbx_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbx_asuntosP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbx_asuntosS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_guardar, btn_quitar, btn_volver});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbx_asuntosP, cmbx_asuntosS, cmbx_usuarios});

    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        mainFrame.menuPrincipal();
        this.setVisible(false);
        estePanel = null;
        System.gc();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void cmbx_asuntosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_asuntosPActionPerformed
        // TODO add your handling code here:
        cmbx_asuntosS.setVisible(true);
        cargarComboBoxAsuntoS();
    }//GEN-LAST:event_cmbx_asuntosPActionPerformed

    private void cmbx_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_usuariosActionPerformed
        // TODO add your handling code here:
        cmbx_asuntosP.setVisible(true);
        lbl_asuntos.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_cmbx_usuariosActionPerformed

    private void cmbx_asuntosSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_asuntosSActionPerformed
        // TODO add your handling code here:
        btn_agregar.setVisible(true);
    }//GEN-LAST:event_cmbx_asuntosSActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(mainFrame, "Seguro desea agregar este asunto?", "Seguro", JOptionPane.YES_NO_OPTION) == 0) {
            Usuario miUsuario = (Usuario) cmbx_usuarios.getSelectedItem();
            miUsuario.getAsuntoSecundarioCollection().add((AsuntoSecundario) cmbx_asuntosS.getSelectedItem());
            serviciosU = new UsuarioServ();
            if (serviciosU.modificarUsuario(miUsuario) == 0) {
                JOptionPane.showMessageDialog(mainFrame, "Asunto agregado!");
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(mainFrame, "Error al agregar asunto!");
            }

        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarActionPerformed
        // TODO add your handling code here:
        if((jt_asuntos.getSelectedRow() != -1)&&(jt_asuntos.getSelectedRowCount() == 1)){
            if(JOptionPane.showConfirmDialog(mainFrame, "Seguro desea quitar este asunto?") == 0){
                serviciosU = new UsuarioServ();
                serviciosA = new AsuntoSecundarioServ();
                serviciosP = new AsuntoPrincipalServ();
                
                Usuario miUsuario = (Usuario) cmbx_usuarios.getSelectedItem();
                
                List <AsuntoSecundario> asuntos = serviciosA.traerTodos();
                List <AsuntoPrincipal> asuntoP = serviciosP.traerTodos();
                AsuntoSecundario miAsu = new AsuntoSecundario();
                AsuntoPrincipal miAsup = new AsuntoPrincipal();
                
                for(int i = 0; i < asuntoP.size(); i ++ ){
                    if(asuntoP.get(i).getNombre().equals(modelo.getValueAt(jt_asuntos.getSelectedRow(), 0))){
                        miAsup = asuntoP.get(i);
                    }
                }
                
                for(int i = 0; i < asuntos.size(); i++){
                    if((asuntos.get(i).getNombreasuntoS().equals(modelo.getValueAt(jt_asuntos.getSelectedRow(), 1).toString()))
                        &&(asuntos.get(i).getPertenece().equals(miAsup))){
                        miAsu = asuntos.get(i);
                    }
                }
                miUsuario.getAsuntoSecundarioCollection().remove(miAsu);
                serviciosU = new UsuarioServ();
                if (serviciosU.modificarUsuario(miUsuario) == 0) {
                    JOptionPane.showMessageDialog(mainFrame, "Asunto quitado!");
                    cargarTabla();
                } else {
                    JOptionPane.showMessageDialog(mainFrame, "Error al quitar asunto!");
                }
            }
        }
    }//GEN-LAST:event_btn_quitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox cmbx_asuntosP;
    private javax.swing.JComboBox cmbx_asuntosS;
    private javax.swing.JComboBox cmbx_usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_asuntos;
    private javax.swing.JLabel lbl_asuntos;
    private javax.swing.JLabel lbl_asuntos1;
    // End of variables declaration//GEN-END:variables
}
